### ISSUE TITLE
webpack 2?

### ISSUE THREAD

**Issue by socketwiz** [prashaantt/hapi-webpack-hot-middleware#2]
> Upgraded to use Webpack 2.

Why would you make Webpack 2 the default when version 2 is still in beta?

**Comment by prashaantt** [comment]
I needed to try it for one of my projects. The 1.x version should work with Webpack 1 just as before.

**Comment by socketwiz** [comment]
OK, thanks.  I think my problem was not having all the loaders that I needed installed.  But I was starting to think it had something to do with the webpack version.
